import "@/components/auth/auth.css";
import { cn } from "@/lib/utils";
import Providers from "@/store/Providers";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: " User MotorCut",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <meta name="author" content="Muhammad Afrasyab & Muhammad Osama" />
          <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Noto+Sans:wght@400;700&display=swap"
            rel="stylesheet"
          />
        
        </head>
        <body className={cn("", montserrat.className)}>
          {children}
        
          <ToastContainer />
        </body>
      </html>
    </Providers>
  );
}
