import "@/components/auth/auth.css";
import { cn } from "@/lib/utils";
import Providers from "@/store/Providers";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: " User MotorCut",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js" defer></script>
          <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.waves.min.js" defer></script>
        </head>
        <body className={cn("", montserrat.className)}>
          {children}

          <ToastContainer />
        </body>
      </html>
    </Providers>
  );
}
